# Generated by Django 4.1 on 2022-09-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prescription", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="prescription", name="name",),
    ]
