# Generated by Django 4.1 on 2022-09-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescription", "0002_remove_prescription_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="uploaded_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
