# Generated by Django 4.0.5 on 2022-10-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_alter_prescription_uploaded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='annotation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
