# Generated by Django 4.0.5 on 2022-10-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_prescription_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medication',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
